# Generated by Django 5.0.7 on 2025-06-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='producto',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['name'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='name',
        ),
        migrations.AddField(
            model_name='compra',
            name='producto_id',
            field=models.IntegerField(default=0, verbose_name='ID del producto'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
