# Generated by Django 5.2 on 2025-06-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_usuarioregistro"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuarioPendiente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=150)),
                ("password", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=254)),
                ("nombre", models.CharField(max_length=150)),
                ("apellido", models.CharField(max_length=150)),
                ("codigo", models.CharField(max_length=10)),
                ("creado", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
