# Generated by Django 5.2 on 2025-06-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_usuariopendiente"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UsuarioPendiente",
        ),
        migrations.AddField(
            model_name="usuarioregistro",
            name="confirmado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usuarioregistro",
            name="odigo_confirmacion",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
