# Generated by Django 5.2 on 2025-06-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_delete_usuariopendiente_usuarioregistro_confirmado_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuarioregistro",
            name="odigo_confirmacion",
        ),
        migrations.AddField(
            model_name="usuarioregistro",
            name="codigo_confirmacion",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
